### ISSUE TITLE
Support decorated providers

### ISSUE THREAD

**Issue by jl-wynen** [scipp/sciline#127]
Currently, providers with decorators are broken:
```python
import sciline as sl
import functools

def deco(f):
    @functools.wraps(f)
    def impl(*args, **kwargs):
        return f(*args, **kwargs)
    return impl

@deco
def foo(x: int) -> str:
    return str(x)

pl = sl.Pipeline([foo], params={int: 3})
pl.compute(str)
```
raises 
```
TypeError: foo() missing 1 required positional argument: 'x'
```

I think this was introduced in #116 because
```python
import functools
import inspect
from typing import get_type_hints

def deco(f):
    @functools.wraps(f)
    def impl(*args, **kwargs):
        return f(*args, **kwargs)
    return impl

@deco
def foo(x: int) -> str:
    return str(x)

print(get_type_hints(foo))
# -> {'x': <class 'int'>, 'return': <class 'str'>}
print(inspect.getfullargspec(foo))
# -> FullArgSpec(args=[], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={'return': <class 'str'>})
```
So using `getfullargspec` is not enough, we also need to use `get_type_hints`.

Unfortunately, this breaks keyword-only args:
```python
@deco
def foo(x: int, *k: float) -> str:
    return str(x)

print(get_type_hints(foo))
# -> {'x': <class 'int'>, 'k': <class 'float'>, 'return': <class 'str'>}
print(inspect.getfullargspec(foo))
# -> FullArgSpec(args=[], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={'return': <class 'str'>})
```

**Comment by jl-wynen** [comment]
To deal with decorators that use `functools.wraps`, we can detect a `__wrapped__` arg and inspect that instead.
But this would not work for other decorators. But that may not matter.
